services:
  - type: web
    name: novel-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 "wsgi:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: DROPBOX_ACCESS_TOKEN
        sync: false