services:
  - type: web
    name: novel-downloader-api
    env: python
    buildCommand: pip install gunicorn flask flask-socketio
    startCommand: gunicorn "wsgi:create_app()" --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000