services:
  - type: web
    name: novel-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8080
      - key: DROPBOX_ACCESS_TOKEN
        sync: false